[project]
name = "chatter-client"
version = "0.1.0"
dependencies = [
  "eclipse-zenoh==1.4.0",
  "pycdr==0.1.5"
]

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
features = ["pyo3/extension-module"]

