[package]
name = "service"
version = "0.1.0"
edition = "2024"

[dependencies]
env_logger = "0.11.8"
log = "0.4.27"
r2r = "0.9.5"
tokio = { version = "1.0", features = ["full", "signal"] }
futures = "0.3"

[build-dependencies]
# r2r needs these for message generation
r2r = "0.9.5"
